const languages = {
    it: {
        login_prompt: "Inserire codice di accesso per stabilire connessione.",
        login_placeholder: "CODICE DI ACCESSO",
        login_button: "ACCEDI",
        admin_access: "[ Accesso Riservato ]",
        security_protocols: "Protocolli di Sicurezza",
        chat_header_channel: "CANALE",
        chat_header_codename: "CODENAME",
        chat_placeholder: "Trasmissione...",
        chat_send_button: "INVIA",
        modal_error_input_title: "ERRORE INPUT",
        modal_error_input_msg: "È necessario inserire un codice di accesso.",
        modal_login_failed_title: "ACCESSO NEGATO",
        modal_login_failed_msg: "Codice non valido o server irraggiungibile.",
        modal_channel_terminated_title: "CANALE TERMINATO",
        modal_channel_terminated_msg: "Questo canale è stato chiuso dall'amministrazione.",
        modal_disclaimer_title: "AVVISO DI SICUREZZA",
        modal_disclaimer_msg: `<p>Questo è un sistema di comunicazione sicuro e non tracciato.</p><ul><li>I messaggi degli operatori si autodistruggono dopo 15 secondi.</li><li>I messaggi dell'amministrazione e i broadcast si autodistruggono dopo 60 secondi.</li><li>Non condividere informazioni personali o sensibili.</li><li>L'amministrazione non è responsabile del contenuto delle conversazioni.</li></ul>`,
        modal_disclaimer_accept_btn: "ACCETTO",
        info_interceptor_title: "Keylogger Etico",
        info_interceptor_msg: "Mostra un feed in tempo reale di ogni singolo messaggio che transita sul server.",
        info_banishment_title: "Protocollo Espulsione",
        info_banishment_msg: "Visualizza tutti gli operatori connessi. Cliccando su [ESPULSIONE], il loro IP verrà bannato permanentemente.",
        info_unban_title: "Gestione Ban",
        info_unban_msg: "Mostra la lista di tutti gli IP bannati e permette di revocare un ban.",
        info_broadcast_title: "Messaggio Broadcast",
        info_broadcast_msg: "Invia un messaggio di massima priorità a tutti gli utenti connessi.",
        info_support_title: "Terminale Assistenza",
        info_support_msg: "Visualizza i ticket di assistenza inviati dagli utenti in tempo reale e permette di rispondere creando un canale di supporto dedicato.",
        info_map: "<strong>Mappa Globale:</strong><br>Visualizza la posizione geografica simulata di ogni operatore. È possibile zoomare e interagire con la mappa.",
        info_integrity: "<strong>System Integrity:</strong><br>Esegue una scansione simulata dei moduli critici del server.",
        info_channels: "<strong>Gestione Canali:</strong><br>Visualizza tutti i codici canale validi, anche quelli vuoti, e permette di eliminarli.",
        info_performance: "<strong>Performance:</strong><br>Monitora in tempo reale l'attività dei messaggi e l'utilizzo simulato di CPU e Memoria del server."
    },
    en: {}
};